/**
 * Created by liekkas on 15/12/17.
 */
export const ActionTypes = {
  INIT_USER: 'INIT_USER',
  THEME_CHANGED: 'THEME_CHANGED',
  SCREEN_RATIO_CHANGED: 'SCREEN_RATIO_CHANGED',
  SCREEN_NUMS_CHANGED: 'SCREEN_NUMS_CHANGED',

  INIT_SCENE: 'INIT_SCENE',
  NEW_SCENE: 'NEW_SCENE',
  EDIT_SCENE: 'EDIT_SCENE',
  SAVE_SCENE: 'SAVE_SCENE',
  SAVE_SUCCESS: 'SAVE_SUCCESS',
  SAVE_FAILURE: 'SAVE_FAILURE',
  DRAG_COMPONENT_INTO_WORKSPACE: 'DRAG_COMPONENT_INTO_WORKSPACE',
  DRAG_PLACER_ON_WORKSPACE: 'DRAG_PLACER_ON_WORKSPACE',
  SAVE_COMPONENT_CONFIG: 'SAVE_COMPONENT_CONFIG',
  REMOVE_PLACER_FROM_WORKSPACE: 'REMOVE_PLACER_FROM_WORKSPACE',
  BRING_PLACER_TO_FRONT: 'BRING_PLACER_TO_FRONT',

  DELETE_SCENE: 'DELETE_SCENE',
  DELETE_GROUP: 'DELETE_GROUP',
  SHOW_SCENE: 'SHOW_SCENE',
};

export function createAction(type, payload = '', meta = '') {
  return {
    type,
    payload,
    meta,
  };
}
