/**
 * Created by liekkas on 15/12/21.
 */

export const GlobalActionTypes = {
  THEME_CHANGED: 'THEME_CHANGED',
  SCREEN_RATIO_CHANGED: 'SCREEN_RATIO_CHANGED',
  SCREEN_NUMS_CHANGED: 'SCREEN_NUMS_CHANGED',
};

export const CurSceneActionTypes = {
  NEW_SCENE: 'NEW_SCENE',
  SAVE_SCENE: 'SAVE_SCENE',
  EDIT_SCENE: 'EDIT_SCENE',
  PREVIEW_UNSAVED_SCENE: 'PREVIEW_UNSAVED_SCENE',
  DRAG_COMPONENT_INTO_WORKSPACE: 'DRAG_COMPONENT_INTO_WORKSPACE',
  DRAG_PLACER_ON_WORKSPACE: 'DRAG_PLACER_ON_WORKSPACE',
  SAVE_COMPONENT_CONFIG: 'SAVE_COMPONENT_CONFIG',
  REMOVE_PLACER_FROM_WORKSPACE: 'REMOVE_PLACER_FROM_WORKSPACE',
};

export const ScenesActionTypes = {
  GET_SCENES_BY_GROUP: 'GET_SCENES_BY_GROUP',
  GET_SCENE_GROUP_NAMES: 'GET_SCENE_GROUP_NAMES',
  GET_SCENES_BY_GROUP_NAME: 'GET_SCENES_BY_GROUP_NAME',
  NEW_SCENE_GROUP: 'NEW_SCENE_GROUP',
  EDIT_SCENE_GROUP_NAME: 'EDIT_SCENE_GROUP_NAME',
  REMOVE_SCENE_GROUP: 'REMOVE_SCENE_GROUP',
  SHOW_SCENE: 'SHOW_SCENE',
};
